{
 "title": "${TERRAFORM_ENVIRONMENT} - AWS ECS",
 "description": "Visualize AWS ECS metrics",
 "tags": [
  "monitoringartist",
  "cloudwatch"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "cloudwatch" },
   { "name": "region", "label": "Region", "query": "regions()" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "dimension_values($region,AWS/ECS,CPUUtilization,ClusterName)"
   },
   {
    "name": "service",
    "label": "Service",
    "query": "dimension_values($region,AWS/ECS,CPUUtilization,ServiceName)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPUUtilization (cluster $cluster, service $service)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "$cluster", "ServiceName": "$service" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "MemoryUtilization (cluster $cluster, service $service)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "$cluster", "ServiceName": "$service" },
     "metricName": "MemoryUtilization",
     "namespace": "AWS/ECS",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "CPUReservation (cluster $cluster)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "$cluster" },
     "metricName": "CPUReservation",
     "namespace": "AWS/ECS",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "MemoryReservation (cluster $cluster)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "$cluster" },
     "metricName": "MemoryReservation",
     "namespace": "AWS/ECS",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  { "title": "Documentation", "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 28 } }
 ]
}